preload.lua
Config has to successfully load and shutdown for history to have a non nil value.
If history is nil then load empty table instead.
=> Handle case where history is `nil`

core.fnl, windows.fnl
- Supports setting window grid dimensions in config.fnl
- Defaults to 0 margin and "3x2" dimension
```clojure
{:grid {:margins [0 0]
:size "3x2"}}
```
=> Added windows grid dimensions to config

spacehammer.el
My memory fails to recall if there's any historical significance of these functions, but I assume they are required for "Org-capture From Anywhere" feature to work properly. Somehow I forgot to move them into spacehammer.el and they remained in my own config.
=> a few org-capture related functions I forgot to move to spacehammer.el

lib/apps.fnl, lib/atom.fnl, lib/functional.fnl, lib/macros.fnl, lib/modal.fnl, lib/text.fnl, windows.fnl
- Removed `,` comma from lib/apps.fnl
- Replaced `@` with `,` comma
- Replace `(# list)` with `(length list)`
- Updated end index calculation in `lib/functional.fnl:slice-start-end` due to unexpected `if` inside a `let`.
Seems to be working for me in 0.3.0 but please confirm :smile:
=> Remove commas for fennel 0.3.0

core.fnl
Fixes agzam/spacehammer#31 where local key bindings and menu items randomly stopped working.
Research suggests the hs.application.watcher instance was garbage-collected
https://github.com/Hammerspoon/hammerspoon/issues/681
Fix creates a global var resources table to store the output of every module.init.
=> Fix local app bindings \ menus

README.ORG, config.fnl, core.fnl
Replaces the custom dir path from `~/.hammerspoon/private` to `~/.spacehammer/`.
- Both setups support source-controlled config
- core.fnl looks for `~/.spacehammer/config.fnl` and `~/.spacehammer/init.fnl`.
Since it works equivalently with either setup, it's up to you @agzam as to which you would prefer.
=> Use ~/.spacehammer config directory

config.fnl
- Fixes agzam/spacehammer#37
- Corrects syntax error in config.fnl caused by poorly resolved merge conflicts
- Please delete your `~/.spacehammer/config.fnl` to re-generate a correctly working version.
=> Fixes default config 

chrome.fnl
- Escaped \ char used in docstring of chrome open location function
=> Fix chrome tab navigation

CHANGELOG.ORG, README.ORG, config.fnl, windows.fnl
- Opening the menu is `alt + space`
- Switching to the previous app is `alt + p`
- Switching to the next app is `alt + n`
Attempts to fix agzam/spacehammer#30
=> Switches default bindings to use the option (alt) key instead of cmd

lib/functional.fnl
A simple compose implementation for functional.fnl.
Takes a list of functions and applies them in reverse order to an input. Very inline with Clojure's `comp` function.
Context in upcoming work:
It was helpful in an upcoming module to read selected text using https://www.hammerspoon.org/docs/hs.uielement.html#selectedText and sending it to a tmux buffer which allows even the most basic of editors to have a REPL experience.
That feature is working on my local but I need to think about how to architect it to make it easy to add support for sending text to other terminals and experiment with copying and reading from the clipboard to get better compatibility with the browser.
=> Add compose function to functional.fnl

windows.fnl
- Fixes agzam/spacehammer#46
- Addresses window jump highlight persisting after many quick jumps
- Creates a var containing a cleanup function and ensures only 1 rect
is displayed at a time
=> Fixes agzam/spacehammer#46 yellow window highlight staying behind

lib/modal.fnl
This is provided by default in many places (vim, evil etc) so it makes sense to include it here too. It's the way I normally use for escape instead of reaching for the esc button.
=> Allow closing modals by ctrl-[

CHANGELOG.ORG, lib/modal.fnl
- Error: last form in a -?>> macro does not receive all args
- Workaround is to add identity function as last form
- Reported upstream in https://github.com/bakpakin/Fennel/issues/276
=> Addresses regression in fennel 0.4.0 in -?>> macro

CHANGELOG.ORG, config.fnl, emacs.fnl
addresses https://github.com/agzam/spacehammer/issues/55
Also removed enabling/disabling editing. That was done initially, (I think) because spawning multiple emacsclient sessions would block the thread. No longer is an issue.
=> feat: Edit-with-emacs detects text selection

config.fnl
Just updating a comment in the default/example config to point to the current private config location as specified in the README.
=> Update comment to point to current private config location

CHANGELOG.ORG, init.lua
- Fixes agzam/spacehammer#68
- Adds support for luarocks with 5.4 which defaults to a local install path 
- Adds support for local luarocks 5.3 for compatability 
1. Download Lua 5.4 from http://www.lua.org/download.html 
2. Extract and cd into lua-5.4.0 
3. Run `make` to build from source
4. Run `make install` to install in expected location on your system. May need to be prefixed with `sudo`.
1. Enter the hammerspoon directory
```bash
cd ~/.hammerspoon/
```
2. Update spacehammer
```bash
git fetch git@github.com:agzam/spacehammer.git master
````
1. Point luarocks to 5.4
```bash
luarocks config lua_version 5.4
```
2. Install fennel
```bash
install fennel
```
=> Fixes agzam/spacehamer#68 support for Hammerspoon 0.9.79 and Lua 5.4

windows.fnl
It looks like there's an issue with moving some windows across screens.
By default, Hammerspoon tries to resize the window (if it is, for example, is
being moved to a display with a smaller resolution).
That, in some cases, forces the window to get resized but not moving onto
another screen (it would keep changing its size but stubbornly stay on the same screen)
Notably, browser windows wouldn't move. I find that it works better if it
doesn't even attempt to resize and would simply move the window.
=> fix moving to another screen

core.fnl, repl.fnl
This adds basic REPL support, built on @eccentric-j 's work.
If you set `:serialize toprint` (or any function that will convert an arbitrary object to a string) in the call to `start` then you can get around it needing serpent entirely, otherwise you need a version of `serpent` that works with Lua 5.4
Requires jeejah-0.3.2 (latest at the time of writing)
My config has this at the bottom, just before the exports section
```lisp
(local repl (require :repl))
(repl.run (repl.start)
```
To test it I bound some keys to start, stop, and check the status:
```lisp
(local repl (require :repl))
(local coroutine (require :coroutine))
(var replserver (repl.start))
(repl.run replserver)
(fn strt [] (set replserver (repl.start)))
(fn run [] (repl.run replserver))
(fn stp [] (repl.stop replserver))
(fn …
```
=> Add basic REPL support.

apps.fnl
- Sets the thumbnail height of the app switcher to half the screen height
- Prepares the calculation function to be advisable once #102 lands
- It was 800 which meant smaller displays would cut-off the horizontal list of apps
Fixes #109
=> Update apps.fnl to calculate switcher thumbnails based on screen height

repl.fnl
Upgraded my fennel package from luarocks to 0.10 but ran into an error about repl.fnl due to the match macro not containing an even number of clauses. The docs suggested prefixing the default value with the key `_`.
Think you could take a quick look @Grazfather?
=> Update repl.fnl to support fennel 0.10

lib/atom.fnl
Noticed after upgrading fennel to v0.10 that the modal system was not working because of an issue copying recursive tables in lib/atom.fnl. This tracks visited tables skipping infinite recursion loops and the stack overflows they cause.
=> Fixes atom copy function in fennel 0.10

apps.fnl, core.fnl
Creates a config option for the window switcher in apps.fnl for custom window filters. Useful if you want the switcher to show minimized apps have other specific app states users wish to target.
The hs app switcher already takes a specialized API hs.window.filter instance so in this case wrapping it in an advisable function seems like indirection without adding much value. The hs.window.filter API is already reasonably well documented https://www.hammerspoon.org/docs/hs.window.filter.html.
Advice could be used if we run into more complex use cases. Or the apps.fnl init function could be made advisable if people wish to override it.
See #109
=> Update apps.fnl to support config for switcher filter

core.fnl, docs/advice.org, lib/advice/init.fnl, lib/advice/macros.fnl, test/advice-test.fnl
Provides a system to wrap or define advisable functions that can be overwritten later. See #72 for intended use case. 
Can solve a number of open PRs by allowing us to wrap some of the internals to support advising. Then users can customize the behaviors by adding advice to their liking. This helps us reduce the number of config settings we need to include for personal preferences.
For example:
We can make the main modal.fnl alert function advisable, then users can add advice to override it so that it displays on all monitors at the same time.
The work here depends on the testing work in #106.
Usage example:
```fennel
(import-macros {: defn
: defadvice} :lib.advice.macros)
(defn original-fn
[x y z]
"docstr"
"Hi")
(original-fn)
;; => "Hi"
(defadvice advice-fn
[x y z]
:override original-fn …
```
=> Advising System

core.fnl, lib/advice/init.fnl, lib/advice/macros.fnl, test/advice-test.fnl
Fixes a small inconsistency in the advice `defadvice` macro + makes the modal function advisable. Includes updates to the tests to catch issues like this in the future.
Fixes #74
Closes #75 
Closes #95 
Then you can add the following to your config.fnl:
```fennel
(require-macros :lib.advice.macros)
(defadvice alert-all-screens
[str style seconds]
:override alert
"Displays an alert across all screens"
(pprint {:str str
:style style
:seconds seconds})
(each [key screen (ipairs (hs.screen.allScreens))]
(hs.alert.show str
style
screen
seconds)))
```
Then the spacehammer modal will display on all screens. @Grazfather may create a follow up PR to add it to the docs as an official, practical example.
The exact cause was due to use the metatables to make the advisable functions callable while …
=> Make alert function advisable + fix advice lib

config.example.fnl, core.fnl, windows.fnl
Fixes #119 
Allows you to add something like the following to your config.fnl:
```fennel
{
;; ...
:modules {:windows  {:center-ratio "50:60"}}
;; ...
}
```
Then you can use the center-window-frame window modal action to use it like the following:
Creates an advisable function called `windows.position-window-center` that takes the center-ratio config string and the target window. It is responsible for parsing the center-ratio string into numbers, and applying them to the target window. The advisable function gives users the option of overriding it to parse the center-ratio string in a different format and apply the calculation differently if needed.
If an option is not set, defaults to `80:50` which is a percentage of the screen. This is nearly identical to the previous version defaults.
=> Fix Center Window Frame function

core.fnl
Quick fix to support loading spoons and accessing them through the `spoon.NAME` global as mentioned in the http://www.hammerspoon.org/docs/hs.html#loadSpoon docs
=> Expose spoons global table to improve spoons compatibility

spacehammer.el
We already expose a hook for when edit-with-emacs starts, `spacehammer/edit-with-emacs-hook`
It gets called at the beginning of the edit and gives users a chance to set frame, buffer and other parameters, major and minor modes, e.g., one may want to set a "distraction free mode", or/and visual-line-mode, etc.
-----
These newly added hooks get called right before closing the edit frame and, for example, can be used like this:
(defun spacehammer-before-finish-edit-with-emacs (bufname pid)
(with-current-buffer bufname
(set-buffer-modified-p nil)))
(add-hook 'spacehammer/before-finish-edit-with-emacs-hook #'spacehammer-before-finish-edit-with-emacs)
In that particular snippet, we mark the buffer as unmodified, so Emacs wouldn't prompt, asking if the file needs saving. It doesn't usually do …
=> Adds a couple of hooks to edit-with-emacs workflow

config.example.fnl, lib/bind.fnl
- Updates bind.fnl error message to be more useful when it can't resolve a string like `windows:undo-action` to a function
- Updates config.example.fnl to point to `windows:undo` instead of `windows:undo-action`
Fixes #127
=> Update bind.fnl error message + windows:undo

emacs.fnl
closes: #126 
It looks like Firefox Developer Edition doesn't allow an immediate access to the
menu after the app gets activated. Adding a tiny delay seems to be fixing the
issue.
=> fix paste phase of edit-with-emacs

lib/modal.fnl
This will prevent hitting leader more than once from doing anything.
=> Split up 'activating' a modal and 'entering' a submenu

README.ORG, repl.fnl
Maybe we don't want this, but we can't nicely support both < 1 and >= 1 because fennel v1.0.0 incorporates `fennelview` into its std.
Actually, according to the [release notes](https://fennel-lang.org/v0.8.0/) it's been that way since v0.8.0.
Most people might not use `repl`, but I don't like that anyone who wants to try it out will be treated to an error. My preference is to simply set a requirement on the minimum fennel version.
=> Only support fennel >= v1.0.0

windows.fnl
I use a bunch of mapping that move the active window to a preset grid (see [here](https://github.com/Grazfather/dotfiles/blob/e95082093c3ff67dfdbfd1d7b42b0170a42a29ef/spacehammer/config.fnl#L239)). In #155 I discovered the `undo` functionality, and would like to use it.
This PR simply adds a function that allows someone to resize a window to a specified grid, but pushes the dimensions onto the history stack so that undo works for it.
=> windows: Add resize-to-grid

lib/apps.fnl, lib/atom.fnl, lib/functional.fnl, lib/text.fnl
Just updated some docs for consistency.
We tend to use singular present tense over imperative, e.g. "Does this" rather than "Do this".
Also fix some wording, formatting, and typos.
=> Update doc strings for consistency

lib/modal.fnl
This allows the user to set `:modal-style` in their config, which will be merged into our default config, allowing them to set any key specified [here](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/alert/alert.lua#L17)
=> Allow config to override modal style

windows.fnl
This function was broken if the user didn't have the windows module set in his config.
=> Fix windows.center-window-frame

README.ORG, docs/emacs.org, spacehammer.el
Edit-With-Emacs feature used to allow to change the major mode and preserve the functionality.
i.e., pressing `C-c C-c` of `spacehammer-edit-with-emacs-mode-map` would finish the edit. That was broken.
Reported by @aisamu in Clojurians Slack:
https://clojurians.slack.com/archives/C099W16KZ/p1697670680745169
=> Emacs: cant change major-mode in edit buffer

emacs.fnl
Fixes: #186 
According the git-blame the couroutine was added to alleviate (perhaps some imaginary problems), back in the day when "edit-with-emacs" was using a separate frame. I think the garbage collector in some cases fails to clean it up. I'm still not completely sure if that's the exact thing that's causing #186, but after removing the coroutine and testing for a couple of days, I'm no longer experiencing the issues described in #186
=> remove needless coroutine

windows.fnl
Alternative to #150  - I noticed jumps weren't working, and went and fixed it before noticing the open PR! This continues using the filter, so will only jump to windows on the current space.
`jump-window` was trying to access a nonexistent `:filter` property of windows instead of `hs.window.filter`. Corrected to instead call `(: hs.window.filter :focusWindow<Dir> <frontmost-window> true true)`.
One minor change from the original is the use of `(hs.window.frontmostWindow)` as the reference window in place of `(hs.window.focusedWindow)`; this will normally use the focused window, but if no window has focus, falls back to the one on "top."
~~Note: Another option would be to use [`(hs.window.filter:focus<Dir>)`](https://www.hammerspoon.org/docs/hs.window.filter.html#focusEast), which calls …
=> bugfix: window jumps

core.fnl
```
% defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"
```
The above allows changing the path to init.lua from the default `~/.hammerspoon` and this tiny change avoids an error in such cases.
=> Fix error on first use with non-default config dir

lib/functional.fnl, test/functional-test.fnl
I just noticed that fennel added `accumulate` in v0.10. We can probably replace many `reduce` calls with it directly, but reduce is still nice.
This change reimplements `reduce` to use `accumulate`, and adds some tests.
=> functional: Re-implement reduce using accumulate

windows.fnl
It looks like the :j / :k assignment has been flipped in `windows.fnl`:
in `config.example.fnl`, :j = "resize-down" and :k = "resize-up"
```
(local window-resize
[...
{:mods [:shift]
:key :j
:action "windows:resize-down"
:repeatable true}
{:mods [:shift]
:key :k
:action "windows:resize-up"
:repeatable true}
...])
```
But this is the reverse (before this PR) in `windows.fnl`:
```
(fn resize-up
[]
(resize-window :j))
(fn resize-down
[]
(resize-window :k))
```
=> windows.fnl: fix resize-{up,down}

windows.fnl
`remove-monitor-items` and `add-monitor-items` are always run in sequence to basically set the monitor items. Using a single function both simplifies the code, and also makes it more understandable.
=> windows.fnl: simply sequence of remove-monitor-items + add-monitor-items -> set-monitor-items
